# Generated by Django 4.2.30 on 2026-06-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('telephone_normalized', models.CharField(blank=True, db_index=True, help_text='Téléphone normalisé pour la recherche webhook', max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp (peut être différent du téléphone)', max_length=50, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscription Bootcamp',
                'verbose_name_plural': 'Inscriptions Bootcamp',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='PaiementBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cyberschool', 'Cyberschool'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('autre', 'Autre')], default='cyberschool', max_length=50)),
                ('montant', models.DecimalField(decimal_places=0, default=100000, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=10)),
                ('reference_transaction', models.CharField(max_length=255, unique=True)),
                ('code_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone_normalized', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='bootcamp_app.inscription')),
            ],
            options={
                'verbose_name': 'Paiement Bootcamp',
                'verbose_name_plural': 'Paiements Bootcamp',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Session 1 — Août 2026', max_length=200)),
                ('date_debut', models.DateField(help_text='Date de début de la session')),
                ('date_fin', models.DateField(help_text='Date de fin de la session')),
                ('places_max', models.PositiveIntegerField(default=5, help_text='Nombre maximum de places')),
                ('prix', models.DecimalField(decimal_places=0, default=100000, help_text='Prix en FCFA (défaut: 100 000)', max_digits=10)),
                ('est_active', models.BooleanField(default=True, help_text='Session visible et ouverte aux inscriptions')),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Bootcamp',
                'verbose_name_plural': 'Sessions Bootcamp',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLogBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cyberschool', 'Cyberschool'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('autre', 'Autre')], default='cyberschool', max_length=50)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ERREUR', 'Erreur'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('code_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone_normalized', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('tentatives', models.IntegerField(default=0)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='bootcamp_app.paiementbootcamp')),
            ],
            options={
                'verbose_name': 'Log Webhook Bootcamp',
                'verbose_name_plural': 'Logs Webhooks Bootcamp',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='bootcamp_app.session'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['telephone_normalized'], name='bootcamp_ap_telepho_f23d86_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['email'], name='bootcamp_ap_email_ca7db5_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['statut'], name='bootcamp_ap_statut_746a43_idx'),
        ),
    ]
