# Generated by Django 4.2.30 on 2026-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberschoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_active', models.BooleanField(default=True, help_text='Configuration active')),
                ('nom', models.CharField(default='Config Cyberschool', help_text='Nom pour identifier cette config', max_length=100)),
                ('lien_moov_money', models.URLField(blank=True, default='', help_text='Lien de paiement Libertis Moov Money (URL Cyberschool)', max_length=500)),
                ('lien_airtel_money', models.URLField(blank=True, default='', help_text='Lien de paiement Libertis Airtel Money (URL Cyberschool)', max_length=500)),
                ('numero_moov', models.CharField(blank=True, default='', help_text='Numéro Moov Money pour paiement direct (ex: 06 XX XX XX XX)', max_length=50)),
                ('numero_airtel', models.CharField(blank=True, default='', help_text='Numéro Airtel Money pour paiement direct (ex: 07 XX XX XX XX)', max_length=50)),
                ('instructions_paiement', models.TextField(blank=True, default='', help_text='Instructions de paiement affichées sur la page de paiement (optionnel)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Cyberschool',
                'verbose_name_plural': 'Configuration Cyberschool',
            },
        ),
    ]
